### ISSUE TITLE
How to upgrade the ASA SDK to version 2.7?

### ISSUE THREAD

**Issue by peterchen2001** [BerwinZ/Multiplayer_AR_Robots_Battle#2]
I got an error message when attempting to reload the anchor from the azure service. I googled the issue and found that the azure service didn't support old ASA SDK, see the link https://github.com/Azure/azure-spatial-anchors-samples/issues/232. 

I tried to upgrade the sample project via the Mixed Reality Feature Tool via https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/welcome-to-mr-feature-tool, but have no ideas on how to proceed, could you guide me how to upgrade the ASA SDK to version 2.7 in this sample project? or do you have time help make an update directly?

**Comment by BowenBZ** [comment]
I think the upgrade of the ASA SDK just requires to install the new version of Unity plugins from the Package Manager, as described in the [step 4](https://github.com/BerwinZ/Multiplayer_AR_Robots_Battle#how-to-set-up-this-project). 

I cannot do the upgrade currently since I don't have a device in hand to test it, but I will do it once I got devices to test it.

**Comment by peterchen2001** [comment]
Thanks for your reply. I have done it by myself.
